In [6]:
from src.data.load_from_binance import load_stocks

In [17]:
s = load_stocks('BTCUSDT', '2023-01-01', '2023-02-01', '1m')

Empty DataFrame
Columns: [begin, open, high, low, close, value]
Index: []

In [18]:
s

,begin,open,high,low,close,value
0,2023-01-01 00:00:00,16541.77000000,16544.76000000,16538.45000000,16543.67000000,83.08143000
1,2023-01-01 00:01:00,16543.04000000,16544.41000000,16538.48000000,16539.31000000,80.45300000
2,2023-01-01 00:02:00,16539.31000000,16541.17000000,16534.52000000,16536.43000000,62.90197000
3,2023-01-01 00:03:00,16536.43000000,16537.28000000,16531.00000000,16533.65000000,115.71894000
4,2023-01-01 00:04:00,16534.12000000,16536.08000000,16527.51000000,16535.38000000,144.45369000
...,...,...,...,...,...,...
44636,2023-01-31 23:56:00,23150.82000000,23151.77000000,23126.94000000,23134.07000000,186.18800000
44637,2023-01-31 23:57:00,23133.44000000,23144.59000000,23130.01000000,23140.33000000,110.49868000
44638,2023-01-31 23:58:00,23140.33000000,23144.61000000,23128.46000000,23131.61000000,163.33895000
44639,2023-01-31 23:59:00,23130.29000000,23133.87000000,23123.23000000,23125.13000000,134.69127000
44640,2023-02-01 00:00:00,23125.13000000,23140.47000000,23124.41000000,23133.74000000,199.09155000

In [9]:
from src.data.preprocessing import data_division

In [11]:
arr_stand, arr_predict, scaler = data_division(data=s, column_value='open', period=20, step=20, \
                                               rolling_period=5, predict_period=10, train_sample=150, column_time='begin', seed=0)

Размер всей выборки: (151, 30)
Размер итоговой выборки: (150, 30, 1)

In [13]:
arr_predict

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,1.738323,2.021211,2.057476,2.091617,1.507993,0.950139,0.618980,0.417768,-0.098880,-0.234096,...,-1.127234,-0.963390,-0.906420,-1.306434,-1.125274,-0.767324,-0.409620,-0.123791,-0.076010,-0.455441
1,-3.647352,-1.382656,0.380231,1.141543,0.874717,0.833681,0.270912,-0.286918,-0.611298,-0.623558,...,0.233451,-0.019241,-0.326423,-0.180154,-0.431314,-0.446298,0.246903,0.932101,1.028478,1.067131
2,0.303049,0.826986,0.969212,1.061025,1.380934,1.303582,0.877746,0.618847,0.412838,0.322560,...,-1.642702,-2.041350,-1.841134,-1.630866,-1.116734,-0.608098,0.127198,0.498510,-0.092529,-1.167345
3,-0.748013,-0.782934,-0.873846,-1.020037,-1.083583,-1.084571,-1.040686,-0.981896,-0.872114,-0.815379,...,0.285337,0.384969,0.501133,0.690452,1.055851,1.383109,1.630928,1.917587,2.174449,2.043334
4,0.229790,0.211106,-0.112852,-0.213872,-0.544480,-1.111962,-1.333951,-1.172763,-0.827588,-0.604649,...,1.506623,0.942942,0.603150,0.329859,-0.519780,-0.810487,-1.189230,-1.288983,-1.414386,-1.013159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,1.699648,0.516990,-0.283999,-0.153423,-0.223550,-0.185260,-1.110289,-1.609161,-1.731502,-1.742921,...,0.999817,0.831163,0.862831,0.260847,-0.351240,-0.942399,-0.883818,-0.778287,-0.220494,0.409719
146,-1.234233,-1.119039,-1.040317,-1.106622,-0.927857,-0.875609,-0.964484,-1.140204,-1.070150,-0.989866,...,1.022006,1.467865,1.606488,1.742612,1.571500,1.494184,1.211939,0.954529,0.741167,0.890411
147,-2.892332,-2.716487,-2.113544,-1.380435,-0.661862,-0.107021,0.192668,0.083680,-0.047888,-0.147611,...,0.293321,0.411054,0.517665,0.572912,0.661117,0.700488,0.404868,0.266017,0.197544,-0.105650
148,2.516763,1.548752,0.497246,0.249899,0.277706,0.583011,0.638397,0.783824,0.917296,1.011157,...,-0.909278,-1.094693,-1.066735,-1.255215,-1.190976,-1.224004,-1.328572,-1.578756,-1.309126,-1.003291
149,1.300267,0.750183,0.682618,0.863323,0.953298,0.958784,0.980816,0.576267,0.469790,0.373131,...,-0.892901,-1.317210,-1.527767,-1.434240,-1.399743,-1.122925,-1.244243,-1.123030,-1.684298,-1.676351